version: '2.4'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: phoyangsa/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSOWRD=vprodbpass

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vproapp:
    build:
      context: ./Docker-file/app
    image: phoyangsa/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata: /usr/local/tomcat/webapps

    vproweb:
      build:
        context: ./Docker-files/webapps
      image: phoyangsa/vprofileweb
      container_name: vproweb
      ports:
        - "80:80"


volumes:
  vprodbdata: {}
  vproappdata: {}